# Generated by Django 5.2.1 on 2025-07-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('email', models.EmailField(max_length=100, unique=True)),
                ('mobno', models.BigIntegerField(unique=True)),
                ('password', models.CharField(max_length=128)),
                ('usertype', models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10)),
            ],
            options={
                'db_table': 'userdata',
            },
        ),
    ]
